### ISSUE TITLE
not working - Error "UnmodifiableListMixin.shuffle"

### ISSUE THREAD

**Issue by eventcatcher** [bibek-ranjan-saha/animated_gradient#1]
#0      UnmodifiableListMixin.shuffle (dart:_internal/list.dart:154:5)
#1      _AnimatedGradientState.build.<anonymous closure>.<anonymous closure> (package:animated_gradient/src/animated_gradient.dart:73:43)

I've changed a few things and it works now:

```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

/// A widget to display animated gradient.
class RoonmatrixAnimatedGradient extends StatefulWidget {
  const RoonmatrixAnimatedGradient({
    super.key,
    this.child,
    this.colors = const [Colors.red, Colors.blue, Colors.green, Colors.yellow],
  });

  final Widget? child;

  final List<Color> colors;

  @override
  RoonmatrixAnimatedGradientState createState() =>
      RoonmatrixAnimatedGradientState();
}

class RoonmatrixAnimatedGradientState
    extends State<RoonmatrixAnimatedGradient> {
  List<Alignment> alignmentList = [
    Alignment.bottomLeft,
    Alignment.bottomRight,
    Alignment.topRight,
    Alignment.topLeft
  ];

  int index = 0;
  Color bottomColor = Colors.transparent;
  Color topColor = Colors.transparent;
  Alignment begin = Alignment.bottomLeft;
  Alignment end = Alignment.topRight;

  @override
  void initState() {
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      if (mounted) {
        setState(
          () {
            topColor = widget.colors.first;
            bottomColor = widget.colors.last;
          },
        );
      }
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(seconds: 2),
      onEnd: () {
        setState(
          () {
            index = index + 1;
            // animate the color
            bottomColor = widget.colors[index % widget.colors.length];
            topColor = widget.colors[(index + 1) % widget.colors.length];

            // animate the alignment
            begin = alignmentList[index % alignmentList.length];
            end = alignmentList[(index + 2) % alignmentList.length];
          },
        );
      },
      decoration: BoxDecoration(
        gradient: LinearGradient(
            begin: begin, end: end, colors: [bottomColor, topColor]),
      ),
      child: widget.child,
    );
  }
}

```

**Comment by cyberalt1** [comment]
ded
